### ISSUE TITLE
Could not load the addon at Anki's starting

### ISSUE THREAD

**Issue by tomboulier** [trgkanki/basic2cloze#2]
# Bug report

Hey! Great idea, I tried to install it from [Anki web](https://ankiweb.net/shared/info/2105427255)

## Describe the bug

After installation, I had an error message telling me that the addon failed to load.

## Reproduction step

1. Install the addon from the official page in [AnkiWeb](https://ankiweb.net/shared/info/2105427255)
2. Restart Anki.

## Expected behavior

The addon should be installed and working after the installation process.

## Actual behavior

The following message appeared in a warning box:

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Automatic Basic to Cloze':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/Users/MyName/Library/Application Support/Anki2/addons21/2105427255/__init__.py", line 17, in <module>
    from .modelFinder import modelExists
  File "/Users/MyName/Library/Application Support/Anki2/addons21/2105427255/modelFinder.py", line 5, in <module>
    from typing import List, Union
ModuleNotFoundError: No module named 'typing'
```

Where, of course, `MyName` has been changed.

## Anki/OS versions

- OS: *macOS Catalina, version 10.15.3 (19D76)*
- Anki version *Version 2.1.13 (3ba55990)*

**Comment by phu54321** [comment]
Sorry for late reply :( haven't checked the email for a while
Will look at it. ETA today
